### ISSUE TITLE
Latex Inside Python Code

### ISSUE THREAD

**Issue by adeptatom** [olivierverdier/python-latex-highlighting#14]
Hello, everyone. This package is great for rendering Python code inside LaTeX. However, I want to be able to insert LaTeX inside the Python code (this has to do with inserting Unicode characters inside (emojis), and I need to stick with pdfLatex, not LuaLatex or XeLaTeX_. How can I go about this?

**Comment by olivierverdier** [comment]
This works fine with XeLaTeX
