### ISSUE TITLE
Missing encoding in pythonhighlight-style

### ISSUE THREAD

**Issue by guironne** [olivierverdier/python-latex-highlighting#21]
By default, it depends the machine...
Accents does not work in utf8econding on windows PC.

**Comment by olivierverdier** [comment]
All machines use utf8 nowadays. There is nothing much more to add in the package to declare that one is using utf8, as far as I know. It would help if you gave some minimal working example showing the problem.

**Comment by guironne** [comment]
line 98 in your file

**Comment by olivierverdier** [comment]
It was actually prepared in my local version, I had forgotten about it. Good call. 👍

Fixed in 2fa0ef5.
