### ISSUE TITLE
Include line numbers

### ISSUE THREAD

**Issue by rebeccaherman1** [olivierverdier/python-latex-highlighting#22]
Is it possible to include automatic line numbers in the rendering? I'm unable to find information on how to do that.

**Comment by olivierverdier** [comment]
You can to that by calling
```tex
\lstset{numbers=left}
```
(after having loaded `pythonhighlight`). 

There are more options available with `\lstset`, see the [`listings` documentation](https://texdoc.org/serve/listings.pdf/0).
