### ISSUE TITLE
Latex Comment inside Python block hides Line

### ISSUE THREAD

**Issue by codingyourlife** [olivierverdier/python-latex-highlighting#3]
I'm not sure if this is a bug and if it is it is laughable small. But found by accident that if you have a latex comment in the first line the second line with code is hidden.

Just try this
```
\begin{python}%[breaklines]
error = y-output
\end{python}
```
->Because of "%[breaklines]" it leads to an empty block instead of a block filled with the single code line

If this is not considered a bug just close the issue...

**Comment by olivierverdier** [comment]
Thank you for noticing this. This is possibly a bug, but it's a bug to report to the maintainer of the main [listings package](https://www.ctan.org/pkg/listings), namely directly to j.hoffmann@fh-aachen.de.
