### ISSUE TITLE
Is this repository up-to-date?

### ISSUE THREAD

**Issue by sblondon** [olivierverdier/python-latex-highlighting#7]
The date included in `pythonhighlight.sty` is 2011/09/19:

> \ProvidesPackage{pythonhighlight}[2011/09/19 

However in the texlive-science package provided by Debian, `pythonhighlight.sty` is 2017.

> % Copyright 2009--2017 by Olivier Verdier
[...]
\ProvidesPackage{pythonhighlight}[2017/02/09

Is this repository the canonical one? Should I use another one?

debian package info: https://packages.debian.org/buster/texlive-science

**Comment by sblondon** [comment]
Comparing the two files with `diff`, the only differences are in the header so there are no real differences.
It still would be nice to update this repository if possible.

**Comment by jansenicus** [comment]
I like this latex style package and I wonder if a placement specifier, caption and label of the listing could also be added.
```
\begin{python}[caption={'A colorful Python code'}, label=lst:nicecode]

    for i, x in enumerate(some_list):
       print(str(i), str(x**2))

\end{python}
```
Those caption and label will serve as an entry in 'List of Codes' just like list of figures, or list of tables.

**Comment by sblondon** [comment]
@jansenicus I'm not sure this package is still maintained. Someone talks to me about `minted` package to highlight code in latex:
https://github.com/gpoore/minted
A lot of languages are available because `minted` uses `pygments`. I don't know if caption or label are implemented.

For info, it's available in Debian in the texlive-latex-extra package (like this library).
